# Generated by Django 3.1 on 2020-08-25 18:18

from django.db import migrations, models
import django.db.models.deletion
import userauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='utils.address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=userauth.models.profile_upload_image_handler),
        ),
    ]
