# Generated by Django 3.1 on 2020-08-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_friend'),
        ('userauth', '0003_auto_20200825_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(null=True, to='utils.Friend'),
        ),
    ]
