# Generated by Django 3.1 on 2020-08-25 18:31

from django.db import migrations, models
import userauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_auto_20200825_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=userauth.models.profile_upload_image_handler),
        ),
    ]
